apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- original.yaml
patches:
- target:
    kind: KubeadmConfigTemplate
    name: d1-md-0
  Patch: |-
    apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
    kind: KubeadmConfigTemplate
    metadata:
      name: d1-md-0
      namespace: default
    spec:
      template:
        spec:
          files:
          - content: 'dev ALL = (ALL) NOPASSWD: ALL'
            owner: root:root
            path: /etc/sudoers.d/dev
            permissions: "0440"
          - contentFrom:
              secret:
                key: worker-node-azure.json
                name: d1-md-0-azure-json
            owner: root:root
            path: /etc/kubernetes/azure.json
            permissions: "0644"
          - path: /etc/containerd/config.toml
            content: |
              ## template: jinja
    
              # Use config version 2 to enable new configuration fields.
              # Config file is parsed as version 1 by default.
              version = 2
    
              imports = ["/etc/containerd/conf.d/*.toml"]
    
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  sandbox_image = "k8s.gcr.io/pause:3.6"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                  runtime_type = "io.containerd.runc.v2"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true
                [plugins."io.containerd.grpc.v1.cri".registry.headers]
                  X-Meta-Source-Client = ["azure/capz"]
                [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
                  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."core.harbor.domain:30003"]
                    endpoint = ["https://core.harbor.domain:30003"]
                  [plugins."io.containerd.grpc.v1.cri".registry.configs]
                    [plugins."io.containerd.grpc.v1.cri".registry.configs."core.harbor.domain:30003".tls]
                      insecure_skip_verify = true
          preKubeadmCommands:
            - echo "172.16.0.4 core.harbor.domain" >>/etc/hosts
          users:
          - name: dev
            sshAuthorizedKeys:
            - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs8UeP9L93kRuHCtb5JoRO+niLg6sxTdzBq3H3Vlcq+yhwWpA6vBm0XcHTS0fwbQJ0TNQAECFEKiFTv8wCRIIi+Y7T/DWXpjYRN6U8BucxCHZs1fLF2bisyvCKFdjJwQdp2+/HycnDodZC98hlvt7MPeZ7S19dq0v5U+lIX+D90heBgZr7h/mgMK/l67oPA0mAIbuVGugHaxDnEQZevI6DmF4XHJdB2Z8ukrGlD5AWevpljRefVOhR+q90U5HQ+qtePTMq5T7mdUSTG73zrIo1+iR8jlSEcPJSnWOwTASQnhgd/W1n3fw/hjHTpdhcUPC/HdgsuMOLnJ/b4Y3iFcOhe2mzqiQlPnyR+BaDKZ3grpHmIV2Dxl6TZ7FltcoEu6i5cTeqL38DcPmaxcFJ9r/03JAPSRzGrToK2kaszrTr95i7oAaXMg8AWtqIRcVLAGE/KGeyBAuPTZYNggF8PITybRTyeD626Yexg7cFiolIcflLJXK+/EqAekkbEendOfs=
    
- target:
    kind: KubeadmControlPlane
    name: d1-control-plane
  Patch: |-
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    metadata:
      name: d1-control-plane
      namespace: default
    spec:
      kubeadmConfigSpec:
        files:
        - contentFrom:
            secret:
              key: control-plane-azure.json
              name: d1-control-plane-azure-json
          owner: root:root
          path: /etc/kubernetes/azure.json
          permissions: "0644"
        - content: 'dev ALL = (ALL) NOPASSWD: ALL'
          owner: root:root
          path: /etc/sudoers.d/dev
          permissions: "0440"
        - path: /etc/containerd/config.toml
          content: |
              ## template: jinja
    
              # Use config version 2 to enable new configuration fields.
              # Config file is parsed as version 1 by default.
              version = 2
    
              imports = ["/etc/containerd/conf.d/*.toml"]
    
              [plugins]
                [plugins."io.containerd.grpc.v1.cri"]
                  sandbox_image = "k8s.gcr.io/pause:3.6"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
                  runtime_type = "io.containerd.runc.v2"
                [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
                  SystemdCgroup = true
                [plugins."io.containerd.grpc.v1.cri".registry.headers]
                  X-Meta-Source-Client = ["azure/capz"]
                [plugins."io.containerd.grpc.v1.cri".registry.mirrors]
                  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."core.harbor.domain:30003"]
                    endpoint = ["https://core.harbor.domain:30003"]
                  [plugins."io.containerd.grpc.v1.cri".registry.configs]
                    [plugins."io.containerd.grpc.v1.cri".registry.configs."core.harbor.domain:30003".tls]
                      insecure_skip_verify = true
        preKubeadmCommands:
          - echo "172.16.0.4 core.harbor.domain" >>/etc/hosts
        users:
        - name: dev
          sshAuthorizedKeys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs8UeP9L93kRuHCtb5JoRO+niLg6sxTdzBq3H3Vlcq+yhwWpA6vBm0XcHTS0fwbQJ0TNQAECFEKiFTv8wCRIIi+Y7T/DWXpjYRN6U8BucxCHZs1fLF2bisyvCKFdjJwQdp2+/HycnDodZC98hlvt7MPeZ7S19dq0v5U+lIX+D90heBgZr7h/mgMK/l67oPA0mAIbuVGugHaxDnEQZevI6DmF4XHJdB2Z8ukrGlD5AWevpljRefVOhR+q90U5HQ+qtePTMq5T7mdUSTG73zrIo1+iR8jlSEcPJSnWOwTASQnhgd/W1n3fw/hjHTpdhcUPC/HdgsuMOLnJ/b4Y3iFcOhe2mzqiQlPnyR+BaDKZ3grpHmIV2Dxl6TZ7FltcoEu6i5cTeqL38DcPmaxcFJ9r/03JAPSRzGrToK2kaszrTr95i7oAaXMg8AWtqIRcVLAGE/KGeyBAuPTZYNggF8PITybRTyeD626Yexg7cFiolIcflLJXK+/EqAekkbEendOfs=
      replicas: 1
    
- target:
    kind: AzureMachineTemplate
    name: d1-md-0
  Patch: |-
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureMachineTemplate
    metadata:
      name: d1-md-0
      namespace: default
    spec:
      template:
        spec:
          dataDisks:
          - diskSizeGB: 256
            lun: 0
            nameSuffix: data
            managedDisk:
              storageAccountType: Standard_LRS
          osDisk:
            diskSizeGB: 128
            managedDisk:
              storageAccountType: StandardSSD_LRS
            osType: Linux
    
- target:
    kind: AzureMachineTemplate
    name: d1-control-plane
  Patch: |-      
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureMachineTemplate
    metadata:
      name: d1-control-plane
      namespace: default
    spec:
      template:
        spec:
          dataDisks:
          - diskSizeGB: 40
            managedDisk:
              storageAccountType: Standard_LRS
            lun: 0
            nameSuffix: etcddisk
          osDisk:
            diskSizeGB: 40
            managedDisk:
              storageAccountType: Standard_LRS
            osType: Linux
