apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: confluent-operator
    confluent-platform: "true"
    cr-name: kafka
    type: kafka
  name: my-cluster-kafka-brokers
  namespace: confluent
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: external
    port: 9092
    protocol: TCP
    targetPort: 9092
  publishNotReadyAddresses: true
  selector:
    app: kafka
    clusterId: confluent
    confluent-platform: "true"
    type: kafka
  sessionAffinity: None
  type: ClusterIP
