apiVersion: batch/v1
kind: Job
metadata:
  name: create-harbor-project-job
  namespace: default
spec:
  template:
    metadata:
      name: create-harbor-project-job
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command:
         - "sh"
         - "-c"
         - "curl -X 'POST' 'https://harbor.harbor.svc.cluster.local/api/v2.0/projects' -H 'Content-Type: application/json' -d '{ \"project_name\": \"test\", \"public\": true, \"storage_limit\": 0 }' -k -u admin:admin"
      restartPolicy: Never


