apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: veri-fluentbit-fluentbit
    app.kubernetes.io/name: fluent-bit
    release: monitoring-prometheus
  name: veri-fluentbit-fluentbit-fluent-bit
  namespace: monitoring
spec:
  endpoints:
  - interval: 5s
    path: /api/v1/metrics/prometheus
    port: http
    scrapeTimeout: 5s
  jobLabel: app.kubernetes.io/instance
  namespaceSelector:
    matchNames:
    - veri
  selector:
    matchLabels:
      app.kubernetes.io/instance: veri-fluentbit-fluentbit
      app.kubernetes.io/name: fluent-bit
