---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: veri-fluentbit-fluentbit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: veri
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.38.0
    helm:
      valueFiles:
      - "$values/{{ .Values.values.path }}/veri-fluentbit/fluentbit.yaml"
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
