---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: harbor
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.14.2
    helm:
      valueFiles:
      - "$values/{{ .Values.values.path }}/harbor/harbor.yaml"
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
