apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-setup-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: istio-setup-role
  namespace: istio-ingress
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-setup-bind
  namespace: istio-ingress
subjects:
  - kind: ServiceAccount
    name: istio-setup-sa
    namespace: default
roleRef:
  kind: Role
  name: istio-setup-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: istio-setup-job-http
  namespace: default
spec:
  template:
    metadata:
      name: istio-setup-job-http
    spec:
      serviceAccountName: istio-setup-sa
      containers:
      - name: tester
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - "kubectl patch service ingress -n istio-ingress -p '{\"spec\":{\"ports\":[{\"name\":\"http2\",\"nodePort\":30080,\"port\":80,\"protocol\":\"TCP\",\"targetPort\":80}]}}'"
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: istio-setup-job-https
  namespace: default
spec:
  template:
    metadata:
      name: istio-setup-job-https
    spec:
      serviceAccountName: istio-setup-sa
      containers:
      - name: tester
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - "kubectl patch service ingress -n istio-ingress -p '{\"spec\":{\"ports\":[{\"name\":\"https\",\"nodePort\":30443,\"port\":443,\"protocol\":\"TCP\",\"targetPort\":443}]}}'"
      restartPolicy: Never


