apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jaeger-operator-ingress-class
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingressclasses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jaeger-operator-ingress-class-binding
subjects:
  - kind: ServiceAccount
    name: tracing-jaeger-operator
    namespace: tracing
roleRef:
  kind: ClusterRole
  name: jaeger-operator-ingress-class
  apiGroup: rbac.authorization.k8s.io
