---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-rook-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: rook-ceph
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://charts.rook.io/release
    chart: rook-ceph
    targetRevision: v1.12.3
    helm:
      valueFiles:
      - "$values/{{ .Values.values.path }}/rook/rook-operator.yaml"
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
