
configs:
- name: default
  deployment: development
  repourl: https://github.com/cal324/apps.git
  values_repourl: https://github.com/cal324/apps.git
  values_path: configs/development
  tasks: [kind, argocd, istio, monitoring]
- name: development
  deployment: development
  targetrevision: develop
  repourl: https://github.com/cal324/apps.git
  values_targetrevision: develop
  values_repourl: https://github.com/cal324/apps.git
  values_path: configs/development
  tasks: [kind, argocd, istio, "@tracing", "@monitoring", "@log-analytics", wave1, "@logging", "@kafka", wave2, "@dummy-nginx", "@kafka-discard", wave3, k6]
- name: performance
  deployment: performance
  targetrevision: main
  repourl: https://github.com/cal324/apps.git
  values_targetrevision: main
  values_repourl: https://github.com/cal324/apps.git
  values_path: configs/performance
  tasks: [cluster_api, capz, argocd, "@istio", "@rook", wave1, "@tracing", "@monitoring", "@log-analytics", wave2, "@logging", "@kafka", wave3, "@dummy-nginx", "@kafka-discard", wave4, k6]
- name: production
  deployment: production
  targetrevision: main
  repourl: https://github.com/cal324/apps.git
  values_targetrevision: main
  values_repourl: https://github.com/cal324/apps.git
  values_path: configs/production
  tasks: [aks, argocd, istio, "@tracing", "@monitoring", "@log-analytics", wave1, "@logging", "@kafka", wave2, "@dummy-nginx", "@kafka-discard", wave3, k6]
