---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confluent-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: confluent
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://packages.confluent.io/helm
    chart: confluent-for-kubernetes
    targetRevision: 0.824.33
    helm:
      valueFiles:
      - "$values/{{ .Values.values.path }}/confluent/operator.yaml"
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
