apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: k6-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","create","patch"]
- apiGroups: ["k6.io"]
  resources: ["k6s"]
  verbs: ["get","create","delete","patch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows","workflowtaskresults"]
  verbs: ["get","create","patch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","create","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k6-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: k6-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: argocd-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["applications"]
  verbs: ["get","create","delete","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-role-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: argocd-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: veri
  name: bit-role
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bit-role-binding
  namespace: veri
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: bit-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: veri
  name: d-role
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: d-role-binding
  namespace: veri
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: d-role
  apiGroup: rbac.authorization.k8s.io
