---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: log-analytics-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: log-analytics
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.26.0
    helm:
      valueFiles:
      - "$values/{{ .Values.values.path }}/log-analytics/loki.yaml"
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
