global:
  proxy:
    resources:
      requests:
        cpu: 10m
pilot:
  autoscaleEnabled: false
  replicaCount: 1
meshConfig:
  defaultConfig:
    tracing:
      sampling: 1
      zipkin:
        address: simplest-collector.tracing.svc.cluster.local:9411
sidecarInjectorWebhook:
  neverInjectSelector:
  - matchExpressions:
    - {key: app, operator: In, values: [kube-prometheus-stack-admission-create,kube-prometheus-stack-admission-patch,startupapicheck]}
