---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-aggregator-fluentbit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: logging
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.34.2
    helm:
      valueFiles:
      - "$values/overlays/fluent-aggregator/files/fluentbit.yaml"
  - repoURL: "{{ .Values.source.repoURL }}"
    targetRevision: "{{ .Values.source.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
