---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-nginx-dummy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: veri
  project: "{{ .Values.project }}"
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    path: overlays/dummy-nginx/dummy
    targetRevision: "{{ .Values.source.targetRevision }}"
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
