---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: tracing
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.12.3
    helm:
      valueFiles:
      - "$values/overlays/tracing/files/{{ .Values.destination.kubernetes }}_cert-manager.yaml"
  - repoURL: "{{ .Values.source.repoURL }}"
    targetRevision: "{{ .Values.source.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
