apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-jaeger-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: tracing
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger-operator
    targetRevision: 2.56.0
    helm:
      valueFiles:
        - $values/{{ .Values.values.path }}/tracing/jaeger-operator.yaml
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
