apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-kiali-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: kiali-operator
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://kiali.org/helm-charts
    chart: kiali-operator
    targetRevision: 2.3.0
    helm:
      valueFiles:
        - $values/{{ .Values.values.path }}/tracing/kiali-operator.yaml
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
