apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tracing-virtualservice
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
  project: "{{ .Values.project }}"
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    path: overlays/tracing/virtualservice
    targetRevision: "{{ .Values.source.targetRevision }}"
  syncPolicy:
    syncOptions:
    automated:
      prune: true
      selfHeal: true
