deploymentMode: SingleBinary
loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: filesystem
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
monitoring:
  serviceMonitor:
    labels: 
      release: monitoring-prometheus
write:
  replicas: 1
read:
  replicas: 1
backend:
  replicas: 1
singleBinary:
  replicas: 1
  autoscaling:
    enabled: true
  persistence:
     size: 50Gi
