loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
monitoring:
  serviceMonitor:
    labels: 
      release: monitoring-prometheus
write:
  replicas: 1
read:
  replicas: 1
backend:
  replicas: 1
singleBinary:
  replicas: 1
  autoscaling:
    enabled: true
  persistence:
     size: 50Gi
