apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/cal324/apps.git
    path: overlays/database
    targetRevision: develop
    helm:
      parameters:
      - name: source.targetRevision
        value: develop
      - name: destination.kubernetes
        value: kind
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
