---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cal324/apps.git
    targetRevision: develop
    path: overlays/capz
    helm:
      parameters:
      - name: source.targetRevision
        value: develop
      - name: destination.kubernetes
        value: capz
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
