apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: development-apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cal324/apps.git
    targetRevision: develop
    path: overlays/development
    helm:
      parameters:
        - name: source.targetRevision
          value: develop
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

