---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-kafka
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: kafka
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://strimzi.io/charts/
    chart: strimzi-kafka-operator
    targetRevision: 0.36.1
    helm:
      valueFiles:
      - "$values/overlays/kafka/files/{{ .Values.destination.kubernetes }}_kafka.yaml"
  - repoURL: "{{ .Values.source.repoURL }}"
    targetRevision: "{{ .Values.source.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
