#! /usr/bin/env ruby
require 'json'

def get_argo_apps(app_name)
  JSON.parse(%x(kubectl get apps -n argocd #{app_name} -o json))['status']['resources'].sort{|a,b|a['syncWave'] <=> b['syncWave']}
end

get_argo_apps('apps').each do |overlays|
  while true
    puts get_argo_apps(overlays['name']).map{|t|"%s(%s)" % [t['name'], t['health']['status']]}.join('-> ')
    break if get_argo_apps(overlays['name']).map{|t|t['health']['status'] == 'Healthy'}.all?
    sleep 10
  end
end
