apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: aggregator-sample-
spec:
  serviceAccountName: default
  entrypoint: whalesay
  arguments:
    parameters:
      - name: global-parameter
        value: hello222
  templates:
    - name: whalesay
      steps:
        - - name: apply-fluentd
            arguments:
              parameters:
              - name: app
                value: veri-fluentd
              - name: targetrevision
                value: develop
              - name: values_targetrevision
                value: HEAD
              - name: values_repourl
                value: https://github.com/cal324/spec.git
              - name: values_path
                value: test
            templateRef:
              name: app
              template: apply-app
        - - name: apply-fluentbit
            arguments:
              parameters:
              - name: app
                value: veri-fluentbit
              - name: targetrevision
                value: develop
              - name: values_targetrevision
                value: HEAD
              - name: values_repourl
                value: https://github.com/cal324/spec.git
              - name: values_path
                value: test
            templateRef:
              name: app
              template: apply-app
        - - name: config-k6
            arguments:
              parameters:
              - name: rate
                value: 100
              - name: duration
                value: 180
            templateRef:
              name: k6
              template: config-k6
        - - name: apply-k6
            templateRef:
              name: k6
              template: apply-k6
        - - name: delete-k6
            templateRef:
              name: k6
              template: delete-k6
        - - name: delete-fluentbit
            arguments:
              parameters:
              - name: app
                value: veri-fluentbit
            templateRef:
              name: app
              template: delete-app
        - - name: delete-fluentd
            arguments:
              parameters:
              - name: app
                value: veri-fluentd
            templateRef:
              name: app
              template: delete-app



