---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: istio-system
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.18.1
    helm:
      valueFiles:
      - "$values/overlays/istio/files/{{ .Values.destination.kubernetes }}_base.yaml"
  - repoURL: "{{ .Values.source.repoURL }}"
    targetRevision: "{{ .Values.source.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
