apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.istio.gateway.sync_wave }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: {{ .Values.global.destination.name }}
  project: {{ .Values.global.project }}
  source:
    repoURL: {{ .Values.global.source.repoURL }}
    path: {{ .Values.global.source.path }}/gateway
    targetRevision: develop
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
