---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: istio-ingress
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.21.1
    helm:
      valueFiles:
      - "$values/{{ .Values.values.path }}/istio/ingress.yaml"
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
