---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ingress
    namespace: istio-ingress
  project: default
  sources:
  - repoURL: https://istio-release.storage.googleapis.com/charts
    chart: gateway
    targetRevision: 1.18.0
    helm:
      valueFiles:
      - "$values/overlays/istio/files/ingress.yaml"
  - repoURL: https://github.com/cal324/apps.git
    targetRevision: develop
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
