apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.istio.ingress_sync_wave }}"
spec:
  destination:
    namespace: istio-ingress
    name: {{ .Values.global.destination.name }}
  project: {{ .Values.global.project }}
  sources:
  - chart: gateway
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.17.3
    helm:
      valueFiles:
        - $values/{{ .Values.global.source.path }}/files/values.yaml
  - repoURL: {{ .Values.global.source.repoURL }}
    targetRevision: {{ .Values.global.source.version }}
    ref: values
  syncPolicy:
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
