apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: base
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.istio.base.sync_wave }}"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: {{ .Values.global.destination.name }}
    namespace: istio-system
  project: {{ .Values.global.project }}
  sources:
  - repoURL: https://istio-release.storage.googleapis.com/charts
    chart: base
    targetRevision: 1.18.0
    helm:
      valueFiles:
        - $values/{{ .Values.global.source.path }}/files/istio-base-values.yaml
  - repoURL: {{ .Values.global.source.repoURL }}
    targetRevision: {{ .Values.global.source.version }}
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: {{ .Values.global.syncPolicy.automated.prune }}
      selfHeal: {{ .Values.global.syncPolicy.automated.selfHeal }}
