apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-tidb-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
  project: "{{ .Values.project }}"
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    path: overlays/database/crd
    targetRevision: "{{ .Values.source.targetRevision }}"
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
