apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database-tidb-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: tidb-admin
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://charts.pingcap.org
    chart: tidb-operator
    targetRevision: v1.6.0
    helm:
      valueFiles:
        - $values/{{ .Values.values.path }}/database/tidb-operator.yaml
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
