---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capz-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
  project: "{{ .Values.project }}"
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    path: overlays/monitoring
    targetRevision: "{{ .Values.source.targetRevision }}"
    helm:
      parameters:
      - name: source.targetRevision
        value: "{{ .Values.source.targetRevision }}"
      - name: destination.kubernetes
        value: capz
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
