kind: "StatefulSet"
podSecurityPolicy:
  enabled: false
service:
  ports: 
   - name: "forwarder"
     protocol: TCP
     containerPort: 24224
   - name: "http"
     protocol: TCP
     containerPort: 8080
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: monitoring-prometheus
    namespace: "monitoring"
  prometheusRule:
    enabled: true
    additionalLabels: 
      release: monitoring-prometheus
    namespace: "monitoring"
    rules:
      - alert: FluentdDown
        expr: up{job="fluentd"} == 0
        for: 5m
        labels:
          context: fluentd
          severity: warning
        annotations:
          summary: "Fluentd Down"
          description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
      - alert: FluentdScrapeMissing
        expr: absent(up{job="fluentd"} == 1)
        for: 15m
        labels:
          context: fluentd
          severity: warning
        annotations:
          summary: "Fluentd Scrape Missing"
          description: "Fluentd instance has disappeared from Prometheus target discovery"
dashboards:
  enabled: "true"
  namespace: "monitoring"

# Resource Configuration
persistence:
  enabled: false

# Using Kubelet to Get Metadata
podAnnotations:
  fluentbit.io/parser: fluentd_parser

# configs
plugins: 
  - fluent-plugin-grafana-loki
configMapConfigs:
  - fluentd-prometheus-conf
fileConfigs:
  01_sources.conf: |-
    <source>
      @type dummy
      dummy {"watchdog": "fluentd"}
      tag watchdog
    </source>

    <source>
      @type forward
    </source>
    
    <source>
      @type http
      port 8080
      bind 0.0.0.0
    </source>

  02_filters.conf: |-
    <filter **>
      @type prometheus
      <metric>
        name fluentd_input_status_num_records_total
        type counter
        desc The total number of incoming records
        <labels>
          tag ${tag}
          hostname ${hostname}
        </labels>
      </metric>
    </filter>

  03_dispatch.conf: |-

  04_outputs.conf: |-
    <match **>
      @type copy
      <store>
        @type loki
        url http://log-analytics-loki-gateway.log-analytics.svc
        extract_kubernetes_labels true
        remove_keys kubernetes,stream,time,_p
        drop_single_key true
        extra_labels {"env":"dev"}
        <label>
          pod_name $.kubernetes.pod_name
          namespace_name $.kubernetes.namespace_name
          host $.kubernetes.host
          container_name $.kubernetes.container_name
          loglevel $.loglevel
        </label>
        flush_interval 1s
      </store>
      <store>
        @type prometheus
        <metric>
          name fluentd_output_status_num_records_total
          type counter
          desc The total number of outgoing records
          <labels>
            tag ${tag}
            hostname ${hostname}
          </labels>
        </metric>
      </store>
    </match>
