serviceMonitor:
  enabled: true
  namespace: monitoring
  interval: 10s
  scrapeTimeout: 10s
  jobLabel: fluentbit
  selector:
    release: monitoring-prometheus
prometheusRule:
  enabled: true
  namespace: "monitoring"
  additionalLabels:
    release: monitoring-prometheus
  rules:
  - alert: NoOutputBytesProcessed
    expr: rate(fluentbit_output_proc_bytes_total[5m]) == 0
    annotations:
      message: |
        Fluent Bit instance {{ $labels.instance }}'s output plugin {{ $labels.name }} has not processed any
        bytes for at least 15 minutes.
      summary: No Output Bytes Processed
    for: 15m
    labels:
      severity: critical
dashboards:
  enabled: true
  namespace: "monitoring"

# Scheduling fluentbit on the control plane
nodeSelector:
  kubernetes.io/os: linux
tolerations:
- effect: NoSchedule
  operator: Exists

# Using Kubelet to Get Metadata
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
podAnnotations:
  fluentbit.io/parser: fluentbit_parser
rbac:
  nodeAccess: true

# configs
config:
  inputs: |
    [INPUT]
        Name dummy
        Dummy {"watchdog": "fluent-bit"}
        Tag watchdog

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

  filters: |
    [FILTER]
        Name grep
        Match kube.*
        Exclude log container

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On
        Use_Kubelet On
        Kube_URL https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
        tls.verify Off
        Buffer_Size 0
        Kubelet_Port 10250

  outputs: |
    [OUTPUT]
        Name forward
        Match *
        Host logging-fluentd.logging.svc
        Port 24224

  customParsers: |
    [PARSER]
        Name fluentd_parser
        Format regex
        Regex ^(?<time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} \+\d{4}) \[(?<loglevel>\w+)\]:\s*(?<log>.*)
        Time_Key time
        Time_Format %Y-%m-%d %H:%M:%S %z

    [PARSER]
        Name fluentbit_parser
        Format regex
        Regex ^\[(?<time>[^\]]+)\] \[\s*(?<loglevel>[^\]]+)\]\s*(?<log>.*)
        Time_Key time
        Time_Format %Y/%m/%d %H:%M:%S

