toolbox:
  resources:
    requests:
      cpu: 10m
cephClusterSpec:
  resources:
    mgr:
      requests:
        cpu: 10m
    mon:
      requests:
        cpu: 10m
    osd:
      requests:
        cpu: 10m
    prepareosd:
      requests:
        cpu: 10m
    mgr-sidecar:
      requests:
        cpu: 10m
    crashcollector:
      requests:
        cpu: 10m
    logcollector:
      requests:
        cpu: 10m
    cleanupn:
      requests:
        cpu: 10m
