apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-fluentd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: logging
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://fluent.github.io/helm-charts
    chart: fluentd
    targetRevision: 0.5.2
    helm:
      valueFiles:
        - $values/{{ .Values.values.path }}/logging/fluentd.yaml
  - repoURL: "{{ .Values.values.repoURL }}"
    targetRevision: "{{ .Values.values.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    automated:
      prune: true
      selfHeal: true
