---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: monitoring
  project: "{{ .Values.project }}"
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-47.1.0
  syncPolicy:
    syncOptions:
    - Replace=true
    directory:
      recurse: true
    automated:
      prune: true
      selfHeal: true
