---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-jaeger-simplest
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '4'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
  project: "{{ .Values.project }}"
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    path: overlays/monitoring/jaeger-simplest
    targetRevision: "{{ .Values.source.targetRevision }}"
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
