---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: monitoring
  project: default
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.6.1
    helm:
      valueFiles:
      - "$values/overlays/monitoring/files/loki.yaml"
  - repoURL: https://github.com/cal324/apps.git
    targetRevision: develop
    ref: values
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
