---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: monitoring
  project: "{{ .Values.project }}"
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.15.0
    helm:
      valueFiles:
      - "$values/overlays/monitoring/files/{{ .Values.destination.kubernetes }}_loki.yaml"
  - repoURL: "{{ .Values.source.repoURL }}"
    targetRevision: "{{ .Values.source.targetRevision }}"
    ref: values
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
