
configs:
- name: default
  deployment: development
  repourl: https://github.com/cal324/apps.git
  values_repourl: https://github.com/cal324/apps.git
  values_path: configs/development
  tasks: [kind, argocd, istio, monitoring]
- name: development
  deployment: development
  targetrevision: develop
  repourl: https://github.com/cal324/apps.git
  values_targetrevision: develop
  values_repourl: https://github.com/cal324/apps.git
  values_path: configs/development
  tasks: [kind, argocd, istio, "@tracing", "@monitoring", wave1, "@fluent-aggregator", "@database", "@kafka", wave2]
- name: performance
  deployment: performance
  targetrevision: performance
  repourl: https://github.com/cal324/apps.git
  values_targetrevision: performance
  values_repourl: https://github.com/cal324/apps.git
  values_path: configs/performance
  tasks: [cluster_api, capz, argocd, "@istio", "@rook", wave1, "@tracing", "@monitoring", wave2, "@fluent-aggregator", "@database", "@kafka", wave3]
- name: production
  deployment: production
  targetrevision: production
  repourl: https://github.com/cal324/apps.git
  values_targetrevision: production
  values_repourl: https://github.com/cal324/apps.git
  values_path: configs/production
  tasks: [aks, argocd, istio, "@tracing", "@monitoring", wave1, "@fluent-aggregator", "@database", "@kafka", wave2]
