apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <%= name %>
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
  project: default
  source:
    repoURL: https://github.com/cal324/apps.git
    path: overlays/<%= name %>
    targetRevision: <%= revesion %>
    helm:
      parameters:
      - name: source.targetRevision
        value: <%= revesion %>
      - name: destination.kubernetes
        value: <%= kubernetes %>
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
