global:
  project: .Values.project
  destination-name: .Values.destination.name
  destination-kubernetes: .Values.destination.kubernetes
  source-targetRevision: .Values.source.targetRevision
  source-repoURL: .Values.source.repoURL
  values-values-targetRevision: .Values.values.targetRevision
  values-repoURL: .Values.values.repoURL
  values-path: .Values.values.path

values:
  - istio:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/istio

      base:
        type: helm
        metadata-annotations-sync-wave: 1
        destination-namespace: istio-system
        source-repoURL: https://istio-release.storage.googleapis.com/charts
        source-chart: base
        syncPolicy-syncOptions-CreateNamespace: true

      istiod:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: istio-system
        source-repoURL: https://istio-release.storage.googleapis.com/charts
        source-chart: istiod

      ingress:
        type: helm
        metadata-annotations-sync-wave: 3
        destination-namespace: istio-ingress
        source-repoURL: https://istio-release.storage.googleapis.com/charts
        source-chart: gateway

      namespace:
        type: kustomization
        metadata-annotations-sync-wave: 1
        source-path: overlays/istio/namespace

      gateway:
        type: kustomization
        metadata-annotations-sync-wave: 4
        source-path: overlays/istio/gateway

  - monitoring:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/monitoring

      prometheus:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: monitoring
        source-repoURL: https://prometheus-community.github.io/helm-charts
        source-chart: kube-prometheus-stack
        syncPolicy-syncOptions-ServerSideApply: true

      namespace:
        type: kustomization
        metadata-annotations-sync-wave: 1
        source-path: overlays/monitoring/namespace

      virtualservice:
        type: kustomization
        metadata-annotations-sync-wave: 3
        source-path: overlays/monitoring/virtualservice

      monitor:
        type: kustomization
        metadata-annotations-sync-wave: 3
        source-path: overlays/monitoring/monitor

  - log-analytics:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/log-analytics

      namespace:
        type: kustomization
        metadata-annotations-sync-wave: 1
        source-path: overlays/log-analytics/namespace

      loki:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: log-analytics
        source-repoURL: https://grafana.github.io/helm-charts
        source-chart: loki
        syncPolicy-syncOptions-ServerSideApply: true

  - tracing:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/tracing

      namespace:
        type: kustomization
        metadata-annotations-sync-wave: 1
        source-path: overlays/tracing/namespace

      cert-manager:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: tracing
        source-repoURL: https://charts.jetstack.io
        source-chart: cert-manager
        syncPolicy-syncOptions-ServerSideApply: true

      jaeger-operator:
        type: helm
        metadata-annotations-sync-wave: 3
        destination-namespace: tracing
        source-repoURL: https://jaegertracing.github.io/helm-charts
        source-chart: jaeger-operator
        syncPolicy-syncOptions-ServerSideApply: true

      jaeger-simplest:
        type: kustomization
        metadata-annotations-sync-wave: 4
        source-path: overlays/tracing/jaeger-simplest

      kiali-operator:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: kiali-operator
        source-repoURL: https://kiali.org/helm-charts
        source-chart: kiali-operator
        syncPolicy-syncOptions-ServerSideApply: true
        syncPolicy-syncOptions-CreateNamespace: true

      kiali:
        type: kustomization
        destination-namespace: istio-system
        metadata-annotations-sync-wave: 3
        source-path: overlays/tracing/kiali

      virtualservice:
        type: kustomization
        metadata-annotations-sync-wave: 3
        source-path: overlays/tracing/virtualservice

  - fluent-aggregator:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/fluent-aggregator

      namespace:
        type: kustomization
        metadata-annotations-sync-wave: 1
        source-path: overlays/fluent-aggregator/namespace

      dummy:
        type: kustomization
        metadata-annotations-sync-wave: 1
        destination-namespace: logging
        source-path: overlays/fluent-aggregator/dummy

      fluentd:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: logging
        source-repoURL: https://fluent.github.io/helm-charts
        source-chart: fluentd

      fluentbit:
        type: helm
        metadata-annotations-sync-wave: 3
        destination-namespace: logging
        source-repoURL: https://fluent.github.io/helm-charts
        source-chart: fluent-bit

  - database:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/database

      tidb-crd:
        type: kustomization
        metadata-annotations-sync-wave: 1
        source-path: overlays/database/crd
        syncPolicy-syncOptions-ServerSideApply: true

      tidb-operator:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: tidb-admin
        source-repoURL: https://charts.pingcap.org
        source-chart: tidb-operator
        syncPolicy-syncOptions-CreateNamespace: true

      tidb-cluster:
        type: kustomization
        metadata-annotations-sync-wave: 3
        destination-namespace: tidb
        source-path: overlays/database/cluster
        syncPolicy-syncOptions-CreateNamespace: true

      nodeport:
        type: kustomization
        metadata-annotations-sync-wave: 4
        destination-namespace: tidb
        source-path: overlays/database/nodeport

  - rook:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/rook

      rook-operator:
        type: helm
        metadata-annotations-sync-wave: 1
        destination-namespace: rook-ceph
        source-repoURL: https://charts.rook.io/release
        source-chart: rook-ceph
        syncPolicy-syncOptions-CreateNamespace: true

      rook-cluster:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: rook-ceph
        source-repoURL: https://charts.rook.io/release
        source-chart: rook-ceph-cluster

  - kafka:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/kafka

      namespace:
        type: kustomization
        metadata-annotations-sync-wave: 1
        source-path: overlays/kafka/namespace

      kafka:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: kafka
        source-repoURL: https://strimzi.io/charts/
        source-chart: strimzi-kafka-operator

      cluster:
        type: kustomization
        metadata-annotations-sync-wave: 3
        destination-namespace: kafka
        source-path: overlays/kafka/cluster

      topic:
        type: kustomization
        metadata-annotations-sync-wave: 4
        destination-namespace: kafka
        source-path: overlays/kafka/topic

