global:
  project: default
  destination-name: in-cluster
  source-targetRevision: develop
  source-repoURL: https://github.com/cal324/apps.git

values:
- istio:
    common:
      syncPolicy-automated-prune: true
      syncPolicy-automated-selfHeal: true
      path: overlays/istio

    base:
      type: helm
      metadata-annotations-sync-wave: 0
      destination-namespace: istio-system
      source-repoURL: https://istio-release.storage.googleapis.com/charts
      source-targetRevision: 1.18.0
      source-chart: base
      syncPolicy-syncOptions-CreateNamespace: true

    istiod:
      type: helm
      metadata-annotations-sync-wave: 0
      destination-namespace: istio-system
      source-repoURL: https://istio-release.storage.googleapis.com/charts
      source-targetRevision: 1.18.0
      source-chart: istiod

    ingress:
      type: helm
      metadata-annotations-sync-wave: 1
      destination-namespace: istio-ingress
      source-repoURL: https://istio-release.storage.googleapis.com/charts
      source-targetRevision: 1.18.0
      source-chart: gateway

    namespace:
      type: kustomization
      metadata-annotations-sync-wave: 0
      source-path: overlays/istio/namespace

    gateway:
      type: kustomization
      metadata-annotations-sync-wave: 2
      source-path: overlays/istio/gateway

- monitoring:
    common:
      syncPolicy-automated-prune: true
      syncPolicy-automated-selfHeal: true
      path: overlays/monitoring

    crd:
      type: crd
      metadata-annotations-sync-wave: 1
      destination-namespace: monitoring
      source-repoURL: https://github.com/prometheus-community/helm-charts.git
      source-path: charts/kube-prometheus-stack/crds/
      source-targetRevision: 46.4.1
      syncPolicy-syncOptions-Replace: true
      syncPolicy-directory-recurse: true

    prometheus:
      type: helm
      metadata-annotations-sync-wave: 2
      destination-namespace: monitoring
      source-repoURL: https://prometheus-community.github.io/helm-charts
      source-targetRevision: 46.4.1
      source-chart: kube-prometheus-stack

    loki:
      type: helm
      metadata-annotations-sync-wave: 3
      destination-namespace: monitoring
      source-repoURL: https://grafana.github.io/helm-charts
      source-targetRevision: 5.6.1
      source-chart: loki

    namespace:
      type: kustomization
      metadata-annotations-sync-wave: 0
      source-path: overlays/monitoring/namespace

    virtualservice:
      type: kustomization
      metadata-annotations-sync-wave: 3
      source-path: overlays/monitoring/virtualservice

