global:
  project: .Values.project
  destination-name: .Values.destination.name
  source-targetRevision: .Values.source.targetRevision
  source-repoURL: .Values.source.repoURL

values:
  - lab:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true

      istio:
        type: kustomization
        metadata-annotations-sync-wave: 0
        source-path: overlays/istio
        source-helm-parameters-source-targetRevision: .Values.source.targetRevision

      monitoring:
        type: kustomization
        metadata-annotations-sync-wave: 0
        source-path: overlays/monitoring
        source-helm-parameters-source-targetRevision: .Values.source.targetRevision

      fluent-aggregator:
        type: kustomization
        metadata-annotations-sync-wave: 1
        source-path: overlays/fluent-aggregator
        source-helm-parameters-source-targetRevision: .Values.source.targetRevision

  - istio:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/istio

      base:
        type: helm
        metadata-annotations-sync-wave: 0
        destination-namespace: istio-system
        source-repoURL: https://istio-release.storage.googleapis.com/charts
        source-chart: base
        syncPolicy-syncOptions-CreateNamespace: true

      istiod:
        type: helm
        metadata-annotations-sync-wave: 0
        destination-namespace: istio-system
        source-repoURL: https://istio-release.storage.googleapis.com/charts
        source-chart: istiod

      ingress:
        type: helm
        metadata-annotations-sync-wave: 1
        destination-namespace: istio-ingress
        source-repoURL: https://istio-release.storage.googleapis.com/charts
        source-chart: gateway

      namespace:
        type: kustomization
        metadata-annotations-sync-wave: 0
        source-path: overlays/istio/namespace

      gateway:
        type: kustomization
        metadata-annotations-sync-wave: 2
        source-path: overlays/istio/gateway

  - monitoring:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/monitoring

      crd:
        type: crd
        metadata-annotations-sync-wave: 1
        destination-namespace: monitoring
        source-repoURL: https://github.com/prometheus-community/helm-charts.git
        source-path: charts/kube-prometheus-stack/crds/
        syncPolicy-syncOptions-Replace: true
        syncPolicy-directory-recurse: true

      prometheus:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: monitoring
        source-repoURL: https://prometheus-community.github.io/helm-charts
        source-chart: kube-prometheus-stack

      loki:
        type: helm
        metadata-annotations-sync-wave: 3
        destination-namespace: monitoring
        source-repoURL: https://grafana.github.io/helm-charts
        source-chart: loki
        syncPolicy-syncOptions-ServerSideApply: true

      namespace:
        type: kustomization
        metadata-annotations-sync-wave: 0
        source-path: overlays/monitoring/namespace

      virtualservice:
        type: kustomization
        metadata-annotations-sync-wave: 3
        source-path: overlays/monitoring/virtualservice

  - fluent-aggregator:
      common:
        syncPolicy-automated-prune: true
        syncPolicy-automated-selfHeal: true
        path: overlays/fluent-aggregator

      namespace:
        type: kustomization
        metadata-annotations-sync-wave: 0
        source-path: overlays/fluent-aggregator/namespace

      dummy:
        type: kustomization
        metadata-annotations-sync-wave: 0
        destination-namespace: default
        source-path: overlays/fluent-aggregator/dummy

      fluentd:
        type: helm
        metadata-annotations-sync-wave: 1
        destination-namespace: logging
        source-repoURL: https://fluent.github.io/helm-charts
        source-chart: fluentd

      fluentbit:
        type: helm
        metadata-annotations-sync-wave: 2
        destination-namespace: logging
        source-repoURL: https://fluent.github.io/helm-charts
        source-chart: fluent-bit
