apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
spec:
  auth:
    strategy: anonymous
  external_services:
    prometheus:
      url: "http://monitoring-prometheus-kube-prometheus.monitoring.svc.cluster.local:9090"
