---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-kafka-dummy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: "{{ .Values.destination.name }}"
    namespace: fluent-kafka
  project: "{{ .Values.project }}"
  source:
    repoURL: "{{ .Values.source.repoURL }}"
    path: overlays/fluent-kafka/dummy
    targetRevision: "{{ .Values.source.targetRevision }}"
  syncPolicy:
    syncOptions: 
    automated:
      prune: true
      selfHeal: true
