alertmanager:
  config:
    route:
      receiver: 'webhook'
      routes:
        - receiver: 'webhook'
    receivers:
    - name: webhook
      webhook_configs:
        - url: "http://logging-fluentd.logging.svc:8080"
grafana:
  adminPassword: admin
  additionalDataSources: 
   - name: loki
     access: proxy
     basicAuth: false
     editable: true
     orgId: 1
     uid: loki
     type: loki
     url: http://loki-gateway.log-analytics.svc
   - name: jaeger
     access: browser
     basicAuth: false
     editable: true
     uid: jaeger
     type: jaeger
     url: simplest-query.tracing.svc.cluster.local:16686
prometheus:
  prometheusSpec:
    storageSpec: 
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    enableRemoteWriteReceiver: true
