name: regression

on:
  push:
    paths:
      - 'base/**'
      - 'overlays/**'
      - 'scripts/**'
      - 'spec/**'
      - '.github/workflows/**'
      - 'Rakefile'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  regression:
    permissions: { contents: read }
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install aqua
        run: |
          curl -sSfL -O https://raw.githubusercontent.com/aquaproj/aqua-installer/v2.3.0/aqua-installer
          echo "1577b99b74751a5ddeea757198cee3b600fce3ef18990540e4d0e667edcf1b5f  aqua-installer" | sha256sum -c
          chmod +x aqua-installer
          ./aqua-installer
          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
          export AQUA_GLOBAL_CONFIG=./spec/aqua.yaml
          aqua i -l
      - name: install ruby
        run: |
          sudo apt install ruby rake jq -y
          sudo gem install rspec -N
      - name: install base
        env:
          ENV: ${{ github.ref_name }}
        run: |
          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
          rake
      - name: test fluent-aggregator
        env:
          ENV: ${{ github.ref_name }}
        run: |
          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
          rake logging
          sleep 180
          rspec spec/post_deploy.spec -e logging
          rake d logging
      - name: test kafka
        env:
          ENV: ${{ github.ref_name }}
        run: |
          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
          rake kafka
          sudo apt install ruby libssl-dev g++ ruby-dev make -y # for kafka
          sudo gem install rdkafka # for kafka
          #sleep 180
          #rspec spec/post_deploy.spec -e kafka
          rake d kafka
      - name: test database
        env:
          ENV: ${{ github.ref_name }}
        run: |
          export PATH="${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}/bin:$PATH"
          #rake database
          #sudo apt install mysql-client -y
          #sleep 180
          #rspec spec/post_deploy.spec -e database

